name: Deploy on push

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy script
        run: /usr/local/bin/deploy-nextapp
